// Record partial generated by RecordGenerator
// WARNING any changes made to this file will be lost when generator is run again

using System;

namespace VertexColoring.Graphs
{
    [System.CodeDom.Compiler.GeneratedCode("RecordGenerator", "0.1.1.29")]
    partial class Edge : IEquatable<Edge>, IComparable<Edge>
    {
        public Edge(Vertex Vertex1, Vertex Vertex2, string Label)
        {
            this.Vertex1 = Vertex1;
            this.Vertex2 = Vertex2;
            this.Label = Label;
        }

        public Edge WithVertex1(Vertex Vertex1)
        {
            return new Edge(Vertex1, Vertex2, Label);
        }

        public Edge WithVertex2(Vertex Vertex2)
        {
            return new Edge(Vertex1, Vertex2, Label);
        }

        public Edge WithLabel(string Label)
        {
            return new Edge(Vertex1, Vertex2, Label);
        }
    }
}