// Record partial generated by RecordGenerator
// WARNING any changes made to this file will be lost when generator is run again

using System;
using System.Collections.Immutable;
using System.IO;

namespace VertexColoring.Graphs
{
    [System.CodeDom.Compiler.GeneratedCode("RecordGenerator", "0.1.1.29")]
    partial class Graph : IEquatable<Graph>
    {
        public Graph(ImmutableSortedSet<Vertex> Vertices, ImmutableSortedSet<Edge> Edges)
        {
            this.Vertices = Vertices;
            this.Edges = Edges;
        }

        public Graph WithVertices(ImmutableSortedSet<Vertex> Vertices)
        {
            return new Graph(Vertices, Edges);
        }

        public Graph WithEdges(ImmutableSortedSet<Edge> Edges)
        {
            return new Graph(Vertices, Edges);
        }
    }
}