// Record partial generated by RecordGenerator
// WARNING any changes made to this file will be lost when generator is run again

using System.Collections.Immutable;

namespace VertexColoring.Graphs
{
    [System.CodeDom.Compiler.GeneratedCode("RecordGenerator", "0.1.1.29")]
    partial class GraphColoring
    {
        public GraphColoring(Graph Graph, IImmutableDictionary<Vertex, int> VertexColors)
        {
            this.Graph = Graph;
            this.VertexColors = VertexColors;
        }

        public GraphColoring WithGraph(Graph Graph)
        {
            return new GraphColoring
(Graph, VertexColors);
        }

        public GraphColoring WithVertexColors(IImmutableDictionary<Vertex, int> VertexColors)
        {
            return new GraphColoring
(Graph, VertexColors);
        }
    }
}