// Record partial generated by RecordGenerator
// WARNING any changes made to this file will be lost when generator is run again

using System;

namespace VertexColoring.Graphs
{
    [System.CodeDom.Compiler.GeneratedCode("RecordGenerator", "0.1.1.29")]
    partial class Vertex : IEquatable<Vertex>, IComparable<Vertex>
    {
        public Vertex(long Id, string Label)
        {
            this.Id = Id;
            this.Label = Label;
        }

        public Vertex WithId(long Id)
        {
            return new Vertex(Id, Label);
        }

        public Vertex WithLabel(string Label)
        {
            return new Vertex(Id, Label);
        }
    }
}